version: '3.4'

services:
  db:
    image: xprtz/mssqldev:latest
    container_name: mssqldev
    ports:
        - "1433:1433"
    build:
      context: .
      dockerfile: Dockerfile
      args:
          ACCEPT_EULA: Y
          SA_PASSWORD: 1234#%*(abcdEFGH
          MSSQL_PID: Developer
          MSSQL_DB: TestDB
          MSSQL_USER: test_db_user
          MSSQL_PASSWORD: T35!DBU53r